# Generated by Django 5.0.7 on 2024-08-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_product_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
