# Generated by Django 5.0.7 on 2024-09-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
