# Generated by Django 5.0.7 on 2024-09-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_is_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_phone_verified',
        ),
    ]
